### ISSUE TITLE
Python client TestDef.py location resolution

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/mtt#673]
The following is the bug I mentioned at last week's telecon, it is also the actual source of #435.

The code I am referring to here is in pyclient/pymtt.py at lines 157-227
## Description of problem:
 - Logic to find the MTT TestDef Class varies based on where code is run from
 - Sets two variables, `basedir` and `topdir`
 - basedir: Directory which should contain the TestDef.py and LoadClasses.py files
 - topdir: Directiory which should contain the default plugins
 - Comment from the code:
```
    # Try to find the MTT TestDef class. Try several methods:

    # 1. If they specified the directory, check it and underneath
    #    it, if necessary
    # 2. See if we are in the MTT home directory by looking for
    #    the MTT plugin directory directly underneath us
    # 3. Check to see if MTT_HOME is set in the environment
    # 4. If $0 is a path, try seeing if that is the place.
```

  - The actual cases which are handled, in order:
    1. If `basedir` is set by --base-dir on launch
       - Check `basedir` for TestDef.py
       - Check `basedir/System`
       - Check `basedir/pylib/System`
       - If found:
         - basedir is the directory containing TestDef.py
         - ***topdir is whatever --base-dir was defined as***
    2. elif "TestDef.py" exists in the current directory
       - topdir = basedir = './' -> 'pylib/System'
       - ***No plugins will be found***
    3. elif "pylib" exists in the current directory
       - basedir = './pylib/System'
       - topdir = './pylib/'
    4. else
       - Try getting the MTT_HOME env variable and using that
         - This is done with a try/except instead of checking if
         if the key exists
         - basedir = '$MTT_HOME/pylib/system'
         - topdir = '$MTT_HOME/pylib'
       - Check if this was called as an absolute path
         - path = dirname $0 (i.e. pyclient/)
         - basedir = 'path/pylib/System' -> 'pyclient/pylib/System'
         - topdir = 'path/pylib' -> 'pyclient/pylib'
         - ***No plugins will be found***
## Possible Solutions:
~~In my eyes, the best solution is to do away with this code entirely.
There are so many assumptions made about the directory structure that
it certainly makes sense to hard code the location of topdir in relation to
the top level directory of the repository.
As for basedir, it is unneeded in my opinion. Since the files in basedir are
mandatory for running the program, they should be in the pyclient directory.
This would allow us to simply `import TestDef` without having to do any class
loading.
While that seems like the logical solution to me,~~ another option is to keep the
existing structure and refactor this code to be consistent ~~and effective~~.
This would be fairly easy to implement, especially if making reasonable
assumptions about the directory structure. Moreso using pathlib's glob
functionality.

@ribab @hppritcha What are your thoughts on this? I don't want to just dive in, let's make sure it is going to work as intended and cover any use case before we change it.

Edit: I think it is also worth discussing the order in which the different cases are handled. One example is that if the environment variable MTT_HOME is set, it is probably not one of the last things we want to check. My proposed order would be:
1. The cli arguments
1. MTT_HOME env variable
1. The canonicalized directory of $0
1. pwd, although I am not sure it is necessary with the prior.

**Comment by rhc54** [comment]
I think you are making a number of assumptions that may be true for the public repo, but might not be true for those who have code in private directories. I'm disturbed by conclusions that the existing code isn't "effective" when at least one organization has been using it "effectively" for more than two years.

It is inevitable that those coming into the code now will find things in the code that don't fit their use-case. However, one must remember that there are those who extend the existing code with a number of proprietary plugins and extensions. Those organizations maintain their code in parallel directory structures - i.e., the code resides in completely independent locations, thus allowing the organizations not to have to worry about colocation of directories.

One example is TestDef, which is not mandated to be the same for everyone using the Python client. 😄 

I'm all in favor of cleaning up code. Let's just not assume that everyone is using it the same way.

**Comment by PeterGottesman** [comment]
You are absolutely correct, effective was definitely not the correct choice of words and I was unaware that TestDef is something which might get overwritten.
This is really the reason I posted this here, I know I am unaware of other's use cases and I want to make sure any possible future changes allow for every possible use case. I clearly made some assumptions I thought were reasonable in my first proposed solution which are not, so that is not really feasible.

Thank you for the input - I wrote this for myself because I was having trouble grokking the code, and it turned into something substantial enough that I thought I would get the community's input on it.

**Comment by rhc54** [comment]
My thinking when architecting the code was based on the observation that the original Perl code had become a tangled web, mostly due to people trying to cram everything into the one code. Hence, we have Jeff's very complex ini files that nobody else can understand.

My thought was to try and instead break things into separable pieces. Thus, everything can be overridden by simply pointing to another directory or directory tree. This allows someone like me (for example) to have a very simple MTT code that my old fossil brain can understand and just run it multiple times, while allowing someone like Jeff to write the more convoluted logic required to execute everything in one giant job.

I could see no reason why everyone would want to push their personal solutions to the repo (and clearly had proprietary cases that would never do so), and so we allowed for the possibility that code might reside "out of sight" in some separable place yet still want to pick/choose from the public code tree. The code that is in the public repo therefore represents a set of generic examples for the various functions - you can build upon them, override them, or use them as-is.

It is certainly true that the generic code tended to get convoluted as people naturally tend to try to "add just one more option" to the existing code (as happened with the Perl code) instead of branching off a derivative version. We should probably try to identify those cases and consider simplifying the code by instead capturing the option in a derivative version.

HTH

**Comment by PeterGottesman** [comment]
That is very helpful, thanks Ralph!

**Comment by jsquyres** [comment]
Per 2018-08-14, we agree that we're just going to require `MTT_HOME` to be set -- it's simpler, smaller code, etc.  @rhc54 is going to check into this (and check to see if the plugin directory CLI option affects this, too, ...etc.).
